version: "3.1"
services:
  apache:
    build: .
    ports: 
      - "9001:80"
    volumes:
      - ./www:/var/www/html/
    links: 
      - db
    networks: 
      - default
    restart: always
  
  db:
    image: mysql:8.0
    ports:
      - "3308:3306"
    command: --default-authentication-plugin=mysql_native_password
    
    
    environment:
      MYSQL_DATABASE: football
      MYSQL_USER: jack
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - ./database:/docker-entrypoint-initdb.d
    networks: 
      - default
    restart: always
    

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - db:db
    ports:
      - "9002:80"
    environment:
      MYSQL_USER: jack
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - default
    restart: always
volumes:
    persistent:

